version: 0.2
phases:
  install:
    commands:
      - echo 'no install script'
  pre_build:
    commands:
      - echo 'no pre_build script'
  build:
    commands:
      - echo 'no build script'
  post_build:
    commands:
      - sh script/deploy.sh
cache:
  paths:
      - echo 'no cache script'
